using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BarrelCtrl : MonoBehaviour
{
    public GameObject expEffect;
    public Texture[] textures;
    private new MeshRenderer renderer;
    private Transform tr;
    private Rigidbody rb;
    private int hitCount = 0;
    // Start is called before the first frame update
    void Start()
    {
        tr = GetComponent<Transform>();
        rb = GetComponent<Rigidbody>();
        renderer = GetComponentInChildren<MeshRenderer>();
        int idx = Random.Range(0,textures.Length);
        renderer.material.mainTexture = textures[idx];
    }
    void OnCollisionEnter(Collision coll)
    {
        if (coll.collider.CompareTag("BULLET"))
        {
            if(++hitCount == 3){
                ExpBarrel();
            }
        }
    }
    void ExpBarrel()
    {
        GameObject exp = Instantiate(expEffect, tr.position,Quaternion.identity);
        Destroy(exp,5.0f);
        rb.mass =1.0f;
        rb.AddForce(Vector3.up * 1500.0f);
        Destroy(gameObject,3.0f);
    }
}